export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  PRODUCT: "/product",
  PRODUCT_DETAIL: "/product/:slug",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:slug",
  CONTACT: "/contact",
  CART: "/cart",
  CHECK_OUT: "/checkout",
  CHECK_OUT_SUCCESS: "/checkout_success",
  DASHBOARD: {
    INDEX: "/dashboard",
    ORDER: "/dashboard/orders",
    ADDRESSES: "/dashboard/addresses",
    WISHLIST: "/dashboard/wishlist",
  },
  FAG: "/fag",
  PAYMENT: "/payment",
  PRIVACY: "/privacy",
  RETURN: "/return",
  SHIPPING: "/shipping",
};
